modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="slamsplushies"
version="1.0.0"
displayName="Slam's Plushies"
authors="RatherChaotic"
credits="Calemi"
description='''

    '''

[[dependencies.slamsplushies]]
modId="calemicore"
mandatory=true
versionRange="1.0.14"
ordering="NONE"
side="BOTH"

[[dependencies.slamsplushies]]
modId="forge"
mandatory=true
versionRange="[40.1.69,)"
ordering="NONE"
side="BOTH"

[[dependencies.slamsplushies]]
modId="minecraft"
mandatory=true
versionRange="1.18.2"
ordering="NONE"
side="BOTH"
